### ISSUE TITLE
Plugin is not compatible with {N} v5.0.0

### ISSUE THREAD

**Issue by OPADA-Eng** [moayadnajd/nativescript-filter-select#57]
The plugin is not working well with nativescript v5 when you select an item and then try to select another one you can't, the select after that freeze and all the items disappear.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2197864/49064002-09ade000-f222-11e8-9ec1-7f166bdd91f0.gif)

**Comment by OPADA-Eng** [comment]
```{
  "nativescript": {
    "id": "com.codeobia.filterselectdemo",
    "tns-ios": {
      "version": "5.0.0"
    },
    "tns-android": {
      "version": "5.0.0"
    }
  },
  "dependencies": {
    "nativescript-filter-select": "1.2.9",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-web-image-cache": "^4.2.2",
    "tns-core-modules": "^5.0.4"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "typescript": "~2.8.2"
  }
}```

**Comment by moayadnajd** [comment]
@OPADA-Eng I need to revamp the plugin and i don't have the time i may do that first quarter of 2019

**Comment by OPADA-Eng** [comment]
@moayadnajd  
Thanks,But it's buggy! 
Is there any work around we can do until that ?

**Comment by simonettoa** [comment]
hi @OPADA-Eng, did you make it works? workaround or something?

cheers

**Comment by Cheaterflums** [comment]
@OPADA-Eng @simonettoa I made some tests and found out that it isn't NativeScript itself that causes this issue, its "tns-core-modules". I downgraded it to version 4.2.1, but stayed at version 5.0.0 for "tns-ios" and "nativescript" and now it is working as expected.

Hope this help you guys too.

**Comment by simonettoa** [comment]
thanks @Cheaterflums, I'll try!

**Comment by OPADA-Eng** [comment]
@Cheaterflums I can't downgrade the hole app to {N} v4 I got a lot of errors.
the nearby solution is to find the piece of code that cause the problem and fix it.

**Comment by Cheaterflums** [comment]
@OPADA-Eng as said, you dont need to downgrade the hole app to v4. its just the tns-core-modules version that needs to be changed.

**Comment by OPADA-Eng** [comment]
I said I tried that, it made me issues in other plugins.

**Comment by suisseworks** [comment]
I have the same issue, need to use tns-core version 5, but tns-select-filter get problems.

**Comment by tylerablake** [comment]
@moayadnajd Any update on this? If you don't have time or haven't started I can try to work on a PR if you need. Thanks!

**Comment by moayadnajd** [comment]
@tylerablake That's will be nice because I don't have time to work on this. I wish I had extra time

**Comment by tahir-jamil** [comment]
Hi @moayadnajd is this fixed for NS 5?

**Comment by tylerablake** [comment]
@tahir-jamil I haven't had time to look into it yet, so I don't think so :(

**Comment by moayadnajd** [comment]
Hi i merged a pull request by @keerl  to fix NS 5 problem i didn't test it but i publish it anyway so please if you can check and let @keerl knows if there something wrong

**Comment by OPADA-Eng** [comment]
@moayadnajd This PR didn't fix the issue totally, there is problem on reselect the element.

**Comment by keerl** [comment]
What is the problem? The reselect problem was fixed for me.

**Comment by moayadnajd** [comment]
@keerl did you test in IOS and Android ? 

@OPADA-Eng Please put more details so @keerl can help 

@keerl thanks for your support here
